[package]
name = "trust-dns-fqdn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trust-dns-proto = { version = "0.22.0", features = ["mdns"] }
rand = "0.8.3"
